### ISSUE TITLE
The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'

### ISSUE THREAD

**Issue by nl80** [gadget-inc/ggt#1457]
### Error ID

95947ed0-3f2b-4814-882b-54d1f06f82bc

### What happened?

When trying to connect to my gadget project i get the following

node_modules/execa/lib/transform/generator.js:1
import {Transform, getDefaultHighWaterMark} from 'node:stream';
                   ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'
    at async Promise.all (index 0)
    at async importCommand (lib/services/command/command.js:44:12)
    at async Module.command (lib/commands/root.js:94:24)
    at async ggt (lib/ggt.js:59:9)
    at async lib/main.js:3:1

### What did you expect to happen?

To connect to gadget project and sync files, i have been doign this successfully previously today

**Comment by scott-rc** [comment]
This error means your version of Node.js is to low. Other users have been able to fix this by updating their Node.js version to v22.

I'm guessing we accidently bumped the minimum required version of Node.js when we updated our `execa` dependency... I'll see if we can revert this and ship another release.
