### ISSUE TITLE
Not able to login using ggt login. Browser authentication redirection is failing

### ISSUE THREAD

**Issue by Shaunakdas** [gadget-inc/ggt#1489]
### Error ID

f3ccee3f-25cc-4385-a44d-80ec6ad7cbc5

### What happened?

Not able to sign in using ggt login. 

Seeing this screen in browser.
<img width="1496" alt="Screenshot 2024-06-17 at 4 58 10 AM" src="https://github.com/gadget-inc/ggt/assets/8094302/938818ef-305a-46eb-a523-9af996225640">

```
We've opened Gadget's login page using your default browser.
Please log in and then return to this terminal.
An unexpected error occurred.
RequestError: self-signed certificate in certificate chain
    at ClientRequest.<anonymous> (node_modules/got/dist/source/core/index.js:792:107)
```

### What did you expect to happen?

I expected to login to ggt.

**Comment by scott-rc** [comment]
That's strange, I have no idea what's causing this 🤔

If you run `ggt login` with the highest verbosity does it show more information? e.g.
```sh
ggt login -vvv
```

**Comment by airhorns** [comment]
I think that error indicates something funky with your local nodejs setup such that something in between you and Gadget is adjusting the SSL certificates. Gadget serves all its content over HTTPS to be secure, and I can confirm our certificates are valid and not self-signed as that error message is saying. Are you potentially running a firewall or corporate proxy or something similar of that nature?
