### ISSUE TITLE
GGT_INTERNAL_ERROR: Can't add new pre-shutdown operations to a TreeOwner that is already shutting down

### ISSUE THREAD

**Issue by fahmeedCodup** [gadget-inc/ggt#1502]
### Error ID

583799b5-8542-451f-a8bd-943f436f87e1

### What happened?

I was developing using sync from Visual Studio Code with Gadget and had modified database schema files for Gadget. When I tried to stash my changes, it pushed them to Gadget. Unfortunately, I had an active ggt dev session running, which pushed the changes and removed all the schema files from Gadget. This resulted in the following error:

GGT_INTERNAL_ERROR: Can't add new pre-shutdown operations to a TreeOwner that is already shutting down

Now, I cannot open the Dev Environment on Gadget because it will not load the app and displays the above error. Additionally, I cannot delete the environment from the Gadget Editor as it prompts for changes to the environment.

### What did you expect to happen?

I expected the changes to be stashed locally without affecting the Gadget environment, especially since the ggt dev session was running. The Dev Environment should have continued functioning without removing the schema files or causing any errors. Additionally, I should be able to delete or modify the environment from the Gadget Editor without encountering errors.

### Steps to reproduce

1. Use Visual Studio Code to sync with Gadget.
2. Modify database schema files for Gadget.
3. Run a ggt dev session.
4. Attempt to stash changes in Visual Studio Code.
5. Observe that the changes are pushed to Gadget, resulting in the removal of schema files.
6. Try to open the Dev Environment on Gadget and observe the error:

GGT_INTERNAL_ERROR: Can't add new pre-shutdown operations to a TreeOwner that is already shutting down

7. Attempt to delete the environment from the Gadget Editor and observe the prompt for changes, preventing deletion.

**Comment by scott-rc** [comment]
Sorry about this! The team is going to investigate this now.

**Comment by Farzaal** [comment]
Any update on this ?

**Comment by MikePresman** [comment]
> Any update on this ?

Hey Farzaal I'm part of the infrastructure team here at Gadget. Would you happen to be on Discord? If so could we chat about this issue? My discord handle is `mikepresman`
