### ISSUE TITLE
We merged your local files with your environment's files 10 times, but your local and environment's files still don't match.

### ISSUE THREAD

**Issue by aurelienbobenrieth** [gadget-inc/ggt#1707]
### Error ID

5e8151e2-b798-49f7-9252-88336d10d798

### What happened?

I cannot seem to determine what started to cause the issue but this is the error message that I get when trying to run `ggt dev` : `We merged your local files with your environment's files 10 times, but your local and environment's files still don't match.`.

It seems like I am able to both pull and push. However I cannot have my `ggt dev` watcher live.

### What did you expect to happen?

Being able to run `ggt dev` as usual.

### Anything else?

Application  musc-intime
Environment  development
     Branch  feature/customer-payment-method-improvements

**Comment by scott-rc** [comment]
So strange, I'm not sure why this happened 🤔 

Please re-open if it happens again.

**Comment by atif089** [comment]
@scott-rc I'm running into the same problem, Error Id `04c2bedf-9033-4097-9e6e-d56841de651a`
