### ISSUE TITLE
[Bug]: 100% CPU usage on Linux

### ISSUE THREAD

**Issue by wooque** [gadget-inc/ggt#209]
### What happened?

After running `ggt sync ./gadget-test` on simple project I can observe ggt process using 100% CPU.
Node.js version is 18.12.0.
OS is Linux (Debian).

### What did you expect to happen?

ggt to be more efficient and to use few CPU cycles for file watching.

### Steps to reproduce

1. Run ggt on simple project - `ggt sync ./gadget-test` 
2. Open some process watched , like htop on Linux and observe ggt CPU usage.

**Comment by scott-rc** [comment]
Hey @wooque 👋 -- sorry for the delay 😞 

I just released v0.1.13 which includes #299 that fixes this issue (thanks @airhorns 🎉 )

You can install the latest version via:

```shell
npm install --global @gadgetinc/ggt
```

If the issue persists after upgrading, please re-open this issue.
