### ISSUE TITLE
sync with latest app failed in local system

### ISSUE THREAD

**Issue by cnviradiya** [gadget-inc/ggt#518]
### Error ID

7f8e3c72-7438-41a7-9f18-ac80af5a782b

### Steps to produce the bug
1. First time install Gadget app in local using @gadgetinc
2. After some day again want to sync so, I run the below command
`npx @gadgetinc/ggt@latest sync --app bulk-discount-generator ./`
3. It's appear the below error:

![image](https://github.com/gadget-inc/ggt/assets/9442993/dac5fcf7-6516-4dc8-889b-52cb1909c32f)

### What did you expect to happen?

It's sync smoothly as We want

### Steps to reproduce

1. Go to root of the pre-installed app in local system
2. After some day again want to sync so, I run the below command
`npx @gadgetinc/ggt@latest sync --app bulk-discount-generator ./`

**Comment by scott-rc** [comment]
When syncing an app to a non-empty directory, `ggt sync` looks for a `.gadget/sync.json` file within said directory. Unfortunately, `.gadget/sync.json` is only created when `ggt sync` is stopped.

I can think of two potential scenarios where `.gadget/sync.json` doesn't exist after previously running `ggt sync`
- You still have `ggt sync` running in another tab
- You stopped `ggt sync`, but it failed to create the `.gadget/sync.json` file

If you **do** have `ggt sync` running in another tab, make sure to stop it via `CTRL+C` before running it again.

If you **don't** have `ggt sync` running you can either:
- re-run the `ggt sync` again with the `--force` flag to force it to continue without a `.gadget/sync.json` file
- `ggt sync` a different directory
- if you don't have any local changes that you want to push, delete the directory and run `ggt sync` again

Let me know if you still have issues

**Comment by scott-rc** [comment]
I was working on saving `.gadget/sync.json` more often in [this PR](https://github.com/gadget-inc/ggt/pull/458) -- I'm gonna  clean it up and release it today.
