### ISSUE TITLE
[Bug]: ggt sync not detecting file changes

### ISSUE THREAD

**Issue by buildpath-ian** [gadget-inc/ggt#540]
### Error ID

no errors

### What happened?

ggt sync doesn't seem to detect local file changes while it's running.

### What did you expect to happen?

I expect that when I edit a file and save it while ggt sync is running, I should see some log of that in terminal, and the change should be pushed to Gadget (remote).

### Steps to reproduce

1. I have an app named 'product-restriction'
2. I want to store app files in a gadget/product-restriction path in the directory I'm running ggt from.
3. So I run npx @gadgetinc/ggt@latest sync --app product-restriction gadget/product-restriction

Here's the log in terminal:

> 
> ggt v0.2.0
> 
> App         product-restriction
> Editor      https://product-restriction.gadget.app/edit
> Playground  https://product-restriction.gadget.app/api/graphql/playground
> Docs        https://docs.gadget.dev/api/product-restriction
> 
> Endpoints
>   - https://product-restriction.gadget.app
>   - https://product-restriction--development.gadget.app
> 
> Watching for file changes... Press Ctrl+C to stop
> 
> Received 1:35:18 PM
> ← .gadget/client/dist-cjs/Client.js (changed)
> ← .gadget/client/dist-cjs/Client.js.map (changed)
> ← .gadget/client/dist-cjs/iife-export.js (changed)
> ← .gadget/client/dist-cjs/iife-export.js.map (changed)
> ← .gadget/client/dist-cjs/index.js (changed)
> ← .gadget/client/dist-cjs/index.js.map (changed)
> ← .gadget/client/dist-cjs/models/CurrentSession.js (changed)
> ← .gadget/client/dist-cjs/models/CurrentSession.js.map (changed)
> ← .gadget/client/dist-cjs/models/Session.js (changed)
> ← .gadget/client/dist-cjs/models/Session.js.map (changed)
> … 315 more
> 325 files in total. 325 changed, 0 deleted.

When I change and save any file such as /frontend/ShopPage.jsx, nothing happens. No recognition of this in terminal. No change reflected on the live app.

### Anything else?

- OS: Windows 11
- yarn installed
- npm installed
- no errors showing anywhere
- no antivirus or security running

**Comment by scott-rc** [comment]
So strange 🤔 

Shot in the dark... but you didn't happen to create a `.ignore` file that ignores everything did you?

**Comment by buildpath-ian** [comment]
@scott-rc  unfortunately not. There is no .ignore file.

**Comment by buildpath-ian** [comment]
@scott-rc UPDATE: I found that if I use the default destination path for the local files including the tilde, the sync works.

I didn't want ggt to put my project in C:\Users\[my username]\gadget\[project-name] because I store all my projects on a separate drive.

So until now, when I ran ggt sync, I had removed the tilde so it would put the local files in the folder I was running the command from instead of in my user folder. But that breaks the syncing.

If I **do** let it put my project in C:\Users\[my username]\gadget\[project-name], sync works. It's very nice. Can't believe I'm developing a shopify app as if I'm working with vite.
I just wish I could keep my project in my preferred drive.

**Comment by scott-rc** [comment]
@DevAOC told me that using `~/` fixed the issue but now I'm even more confused 😅 

We don't want users to **have** to use `~/gadget/[project-name]` for `ggt sync` to work -- it's just a suggested path to quickly get started.

If/when you have a moment, I'm curious if any of these suggestions would also fix the issue:

1. Pass an absolute path to your preferred directory 
	```
	ggt sync --app product-restriction D:\absolute\path\to\product-restriction
	```
2. Create and `cd` into your preferred directory before running `ggt sync`
	```
	mkdir D:\absolute\path\to\product-restriction
	cd D:\absolute\path\to\product-restriction
    ggt sync --app product-restriction
	```

**Comment by buildpath-ian** [comment]
#1 - I will try this and reply back thank you
#2 -  is what I did from the beginning. Running ggt sync from my preferred directory is what led me to create this issue.

**Comment by buildpath-ian** [comment]
@scott-rc  I tried #1 (absolute path) and it doesn't "see" file changes there either. 

So currently, the only way file sync can see changes is if I use the `~/` method to let it put the files in my user  folder.
