### ISSUE TITLE
Bug while working sync on VS Code

### ISSUE THREAD

**Issue by lablack576** [gadget-inc/ggt#576]
### Error ID

6d65b0df-4cc4-4368-a50e-c563bc837bf3

### What happened?

I was working on my Shopify app then suddenly the terminal notified me that the sync has stopped with a text telling THIS IS A BUG and i should submit an issue here !

### What did you expect to happen?

the shopify app get updated according to the code on vs code

### Steps to reproduce

1. Sync your app with vs code using terminal npx @gadgetinc/ggt@latest...
2. Work on your project
3. Suddenly the issue occured
4. btw I was reloading a lots the shopify app navigation page on chrome because it wasn't updating maybe it's because of taht

**Comment by scott-rc** [comment]
We've made a number of improvements to ggt since this issue was opened, in particular:
- https://github.com/gadget-inc/ggt/releases/tag/v0.4.0
- https://github.com/gadget-inc/ggt/releases/tag/v0.4.7

Please retry with the latest version and feel free to re-open this issue if your problems persist.
