### ISSUE TITLE
Deleting Action and Recreating the File Causes Mismatch Between Gadget and VSCode

### ISSUE THREAD

**Issue by mwood23** [gadget-inc/ggt#807]
### Error ID

c767fea5-cb7a-4841-be8f-a92071ccfbd8

### What happened?

I didn't know you couldn't remove the default actions for an entity. I deleted them locally and then noticed they were recreated on the Gadget UI. They didn't sync down though which was bad. So then I made new files locally to copy the ones in the UI.

### What did you expect to happen?

We really need to be able to remove these actions so they aren't exposed to the outside world. I don't want me (or another developer) to accidentally call one of these methods on something should be internal API stuff only.

**Comment by scott-rc** [comment]
The same comment applies to this issue:

https://github.com/gadget-inc/ggt/issues/869#issuecomment-1867861784
