### ISSUE TITLE
Crash when choosing "Reset local files to remote ones"

### ISSUE THREAD

**Issue by avarun42** [gadget-inc/ggt#882]
### Error ID

35b64db2-fca8-450e-915a-20415bf1661b

### What happened?

Gadget crashed while editing local files. Upon restarting, I get the message:
```
Local files have changed since you last synced

? How would you like to proceed?
```
and I choose `Reset local files to remote ones` since I had only made 1 line of changes locally and I'm not sure if there's any remote changes that haven't synced. Upon doing so, I get the error:
```
GGT_CLI_UNEXPECTED_ERROR: An unexpected error occurred

Error: ENOTDIR: not a directory, lstat `{gadget_directory}/.gadget/backup/{gadget_file.ts}
```

Happens every time I try.

### What did you expect to happen?

Expected syncing to work properly.

### Steps to reproduce

1. ggt sync
2. edit local file
3. ggt crashes
4. ggt sync again
5. choose "reset local files to remove ones"

**Comment by scott-rc** [comment]
So sorry about this! The latest version of ggt (v0.3.2) should fix this issue!

Please re-open if this happens again.
